### ISSUE TITLE
How to compile these codes.

### ISSUE THREAD

**Issue by ghost** [Cybellum/DoubleAgent#3]
I'm trying to compile for exe, but whenever I try it's occur error. can you tell me how can compile correctly.

**Comment by MichaelEngstlerCB** [comment]
DoubleAgent compilation should work out of the box without requiring any modifications, did you follow the [Installation](https://github.com/Cybellum/DoubleAgent#installation) steps?
What compiler did you use?
What's the compilation error?

**Comment by samarmeena** [comment]
I'm using Dev c++. and occurred following error while compiling ...

----------------------------------------

In function 'main_Install':
[Error] pasting "L".\\x86\\"" and "DOUBLEAGENT_VERIFIER_DLL_NAME" does not give a valid preprocessing token
[Note] in expansion of macro 'DOUBLEAGENT_VERIFIER_DLL_RELATIVE_PATH_X86'
[Error] pasting "L".\\x64\\"" and "DOUBLEAGENT_VERIFIER_DLL_NAME" does not give a valid preprocessing token
[Note] in expansion of macro 'DOUBLEAGENT_VERIFIER_DLL_RELATIVE_PATH_X64'

----------------------------------------

you can tell me a solution or tell me another compiler that should work perfect for me.

**Comment by ghost** [comment]
Right Now i'm using Microsoft visual studio. and it's occurred a error that v141 build tool not install.

**Comment by MichaelEngstlerCB** [comment]
Dev c++ is not supported, the default compiler we used was [Visual Studio 2017](https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=Community&rel=15).
Regarding v141 build tool, I guess you tried using an older version of VS. There are various solutions for compiling VS 2017 code in older versions of VS, just Google it.

**Comment by ghost** [comment]
i have vs 2015. can i install v141 also known as build tool in vs15

**Comment by MichaelEngstlerCB** [comment]
I guess you can. You can also change the the Platform Toolset from v141 to a lower one in the project properties.

**Comment by ghost** [comment]
okay thanks I understood the issue and Now I can solve it. thanks Michael.
