### ISSUE TITLE
Sample code on DoubleAgentDLL -> main.c

### ISSUE THREAD

**Issue by Fireplop** [Cybellum/DoubleAgent#4]
Hi, i compiled the solution successfully until i uncomment the sample code to launch cmd.exe in  DoubleAgentDll - main.c . 
goto lbl_cleanup; doesn't work as lbl_cleanup is not defined label. On the other hand, if i comment this line and compile, it seems that after launching DoubleAgent_x86.exe and then lauching manually the victim program, cmd.exe doesn't start :/
I am using a windows 7-32bits VM and Visual Studio Pro 2013.
Am i doing something wrong ?
Thanks ;)

**Comment by MichaelEngstlerCB** [comment]
Uncomment "//lbl_cleanup:" that appears just above ["/* Returns status */"](https://github.com/Cybellum/DoubleAgent/blob/master/DoubleAgentDll/main.c).
Note that the sample code currently works on Windows 10 but might not work on older versions of Windows, read [here](https://github.com/Cybellum/DoubleAgent/issues/2#issuecomment-289804888) for more information.

**Comment by Fireplop** [comment]
oh ! I haven't seen this line ... sorry ! For the windows version, i thought the program would have failed, that's why i didn't watch again this discussion. I'll try on win 10 before modifying things for 7. Thanks a lot ;)
