### ISSUE TITLE
Error when testing on Win7 64bit

### ISSUE THREAD

**Issue by Flangvik** [Cybellum/DoubleAgent#5]
Tested working fine on Win10 64 bit (Both the 32 bit and 64 bit release works fine)
However i get the following error when launching the "installed" process on a Win7 64 bit VM box.
This is with the running the example code included (Launching CMD) 

http://vvcap.com/lEvDaIRVdco

**Comment by Flangvik** [comment]
I'm blind, sorry

**Comment by MichaelEngstlerCB** [comment]
More info [here](https://github.com/Cybellum/DoubleAgent/issues/2#issuecomment-289804888).
