### ISSUE TITLE
Unresolved External Symbols when trying to use stdio.h functions.

### ISSUE THREAD

**Issue by FaBeyyy** [Cybellum/DoubleAgent#8]
Im using VS2017, plattform toolset 141, and im getting:

`LNK2001	unresolved external symbol ___acrt_iob_func	DoubleAgentDll	
`
&
`LNK2001	unresolved external symbol ___stdio_common_vfwprintf DoubleAgentDll`

when trying to use `(VOID)wprintf();` or any other print function after including stdio.h in the DoubleAgentDll.

**Comment by MichaelEngstlerCB** [comment]
You need to link against the C Standard Library.

`1. Project Properties -> Linker -> General -> Ignore All Default Libraries = Inherit from parent or project defaults`
`2. Project Properties -> Linker -> Advanced -> Entry Point = Inherit from parent or project defaults`

Note that linking against external libraries (except ntdll.dll) [might cause problems](https://github.com/Cybellum/DoubleAgent/issues/2#issuecomment-289804888) on some versions of Windows (Specifically Windows 7).
